CREATE OR REPLACE FUNCTION SCOTT.FN_PROMEDIO
( P_N1 NUMBER, P_N2 NUMBER,P_N3 NUMBER,P_N4 NUMBER) 
RETURN NUMBER
IS	
	V_PROM NUMBER;
BEGIN
	V_PROM :=(P_N1 + P_N2 + P_N3 + P_N4)/4;
	RETURN V_PROM;
END;
/


SELECT SCOTT.FN_PROMEDIO (8, 10, 5, 6) FROM DUAL;