CREATE OR REPLACE FUNCTION SCOTT.FN_PROMEDIO
( P_N1 NUMBER, P_N2 NUMBER, P_N3 NUMBER, P_N4 NUMBER) 
RETURN NUMBER
IS
	V_PROMEDIO NUMBER;
BEGIN
	V_PROMEDIO := (P_N1 + P_N2 + P_N3 + P_N4) / 4;
	RETURN V_PROMEDIO;
END;

SELECT SCOTT.FN_PROMEDIO (25, 35, 15, 26) FROM DUAL;