/*
===================
PROCESO COMPLEJO
===================

PROCESO REGISTRO DE UNA VENTA

*/

--PROCEDURE ACTUALIZA STOCK

CREATE OR REPLACE PROCEDURE VENTASPLSQL.ACTUALIZA_STOCK(
	P_CODPROD IN VARCHAR,
	P_CANTIDAD IN VARCHAR,
	P_COD_RESPUESTA OUT NUMBER,
  P_MENSAJE 			OUT VARCHAR2)
IS
	V_PRODUCTO VENTASPLSQL.PRODUCTO%ROWTYPE;
	V_NUEVO_STOCK VENTASPLSQL.PRODUCTO.STOCK%TYPE;
BEGIN
	SELECT * INTO V_PRODUCTO
		FROM VENTASPLSQL.PRODUCTO 
		WHERE CODPROD = P_CODPROD
		FOR UPDATE;
	IF P_CANTIDAD > V_PRODUCTO.STOCK THEN
		RAISE_APPLICATION_ERROR(-20035, 'NO HAY STOCK SUFICIENTE');
	END IF;
	V_NUEVO_STOCK := V_PRODUCTO.STOCK - P_CANTIDAD;
	VENTASPLSQL.PKG_PRODUCTO.ACTUALIZAR(V_PRODUCTO.CODPROD,V_PRODUCTO.NOMBRE,V_PRODUCTO.MARCA,V_PRODUCTO.PRECIO,V_PRODUCTO.DESCUENTO,
																			V_NUEVO_STOCK,V_PRODUCTO.DESCRIPCION,V_PRODUCTO.CODCAT,V_PRODUCTO.CODUNI,P_COD_RESPUESTA,
																			P_MENSAJE);
	IF (P_COD_RESPUESTA <> 0) THEN
		RAISE_APPLICATION_ERROR(-20037, P_MENSAJE);
	END IF;
	P_COD_RESPUESTA := 0;
EXCEPTION
	WHEN OTHERS THEN
		P_COD_RESPUESTA := -1;
END;

--PROCEDURE REGISTRA VENTA

CREATE OR REPLACE PROCEDURE VENTASPLSQL.REGISTRAR_VENTA(
	P_CADENA_VENTA 	IN 	VARCHAR2,
	P_COD_RESPUESTA OUT NUMBER,
  P_MENSAJE 			OUT VARCHAR2)
  
IS
  V_CADENA_VENTA VARCHAR2(800);
  V_CLIENTE VARCHAR2(300);
  V_VENTA VARCHAR2(200);
  V_PAGO VARCHAR2(200);
  V_DETALLES VARCHAR2(1000);
  V_FILAS  VENTASPLSQL.PKG_UTIL.T_ARRAY_STRING;
  V_CAMPOS VENTASPLSQL.PKG_UTIL.T_ARRAY_STRING;
  V_COD_RESPUESTA NUMBER := 0;
  V_MENSAJE VARCHAR2(80);
  
BEGIN
	V_CADENA_VENTA := P_CADENA_VENTA;
	
	-- PROCESAR CLIENTE
	V_CLIENTE := VENTASPLSQL.PKG_UTIL.SIGUIENTE_VALOR(V_CADENA_VENTA,'$');
	IF(UPPER(SUBSTR( V_CLIENTE, 1, 1)) = 'S') THEN
		V_CAMPOS := VENTASPLSQL.PKG_UTIL.SPLIT(V_CLIENTE,'|');
		VENTASPLSQL.PKG_CLIENTE.INSERTAR(V_CAMPOS(2),V_CAMPOS(3),V_CAMPOS(4),V_CAMPOS(5),V_CAMPOS(6),V_CAMPOS(7),V_COD_RESPUESTA,V_MENSAJE); 
		IF (V_COD_RESPUESTA <> 0) THEN
			RAISE_APPLICATION_ERROR(-20030, V_MENSAJE);
		END IF;	
	END IF;
	V_CADENA_VENTA := VENTASPLSQL.PKG_UTIL.RESTO(V_CADENA_VENTA,'$');
	
	-- PROCESAR VENTA
	V_VENTA := VENTASPLSQL.PKG_UTIL.SIGUIENTE_VALOR(V_CADENA_VENTA,'$');
	V_CAMPOS := VENTASPLSQL.PKG_UTIL.SPLIT(V_VENTA,'|');
	VENTASPLSQL.PKG_VENTA.INSERTAR(V_CAMPOS(1),SYSDATE,TO_NUMBER(V_CAMPOS(2)),V_CAMPOS(3),V_CAMPOS(4),V_COD_RESPUESTA,V_MENSAJE); 
	IF (V_COD_RESPUESTA <> 0) THEN
		RAISE_APPLICATION_ERROR(-20031, V_MENSAJE);
	END IF;
	V_CADENA_VENTA := VENTASPLSQL.PKG_UTIL.RESTO(V_CADENA_VENTA,'$');
	
	-- PROCESAR PAGO
	V_PAGO := VENTASPLSQL.PKG_UTIL.SIGUIENTE_VALOR(V_CADENA_VENTA,'$');
	V_CAMPOS := VENTASPLSQL.PKG_UTIL.SPLIT(V_PAGO,'|');
	VENTASPLSQL.PKG_PAGO.INSERTAR(SYSDATE,V_CAMPOS(1),V_CAMPOS(2),V_CAMPOS(3),V_CAMPOS(4),V_COD_RESPUESTA,V_MENSAJE); 
	IF (V_COD_RESPUESTA <> 0) THEN
		RAISE_APPLICATION_ERROR(-20032, V_MENSAJE);
	END IF;
	V_CADENA_VENTA := VENTASPLSQL.PKG_UTIL.RESTO(V_CADENA_VENTA,'$');
	
	-- PROCESAR DETALLES
	V_FILAS := VENTASPLSQL.PKG_UTIL.SPLIT(V_CADENA_VENTA,'$');
	FOR I IN 1 .. V_FILAS.COUNT LOOP        
		--VERIFICA Y ACTUALIZA STOCK
		V_CAMPOS := VENTASPLSQL.PKG_UTIL.SPLIT(V_FILAS(I),'|');
  	VENTASPLSQL.ACTUALIZA_STOCK(V_CAMPOS(2),V_CAMPOS(3),V_COD_RESPUESTA,V_MENSAJE);
  	IF (V_COD_RESPUESTA <> 0) THEN
			RAISE_APPLICATION_ERROR(-20033, V_MENSAJE);
		END IF;
    --AÑADE DETALLE
    VENTASPLSQL.PKG_DETALLE_VENTA.INSERTAR(V_CAMPOS(1), V_CAMPOS(2), V_CAMPOS(3), V_CAMPOS(4), V_CAMPOS(5), V_COD_RESPUESTA,V_MENSAJE );
  	IF (V_COD_RESPUESTA <> 0) THEN
			RAISE_APPLICATION_ERROR(-20034, V_MENSAJE);
		END IF;
  END LOOP;
  
  --PROCESO VENTA OK 
	COMMIT;
	P_COD_RESPUESTA := 0;
	P_MENSAJE := 'VENTA CONFORME';
		
EXCEPTION
	WHEN OTHERS THEN
		ROLLBACK;
		P_COD_RESPUESTA := -1;
		P_MENSAJE := TO_CHAR(sqlcode) || ' - ' || SQLERRM;
END;


-- PRUEBA

-- Nuevo cliente

DECLARE
	V_PRUEBA VARCHAR2(1000);
	V_COD_RPTA NUMBER;
	V_MENSAJE VARCHAR2(80);
BEGIN
	DBMS_OUTPUT.PUT_LINE('ENTRO');
	DBMS_OUTPUT.PUT_LINE(' '||TO_NUMBER('51,5'));
--END;
	V_PRUEBA := 'S|68597849|PEREZ AGUILAR|DIEGO|AV LUCCINI 546 SAN ISIDRO|diegoperez@gmail.com|487-4723$VENT20|51,5|FACT001|68597849$51,5|0,0|TOTAL PAGADO|VENT20$VENT20|PROD01|6|6,50|39,00$VENT20|PROD06|2|1,50|3,00';
	VENTASPLSQL.REGISTRAR_VENTA(V_PRUEBA,V_COD_RPTA,V_MENSAJE);
	DBMS_OUTPUT.PUT_LINE('COD: '||V_COD_RPTA);
	DBMS_OUTPUT.PUT_LINE('MENSAJE: '||V_MENSAJE);
END;

-- Cliente existente

DECLARE
	V_PRUEBA VARCHAR2(1000);
	V_COD_RPTA NUMBER;
	V_MENSAJE VARCHAR2(80);
BEGIN
	V_PRUEBA := 'N$VENT30|51,5|FACT007|48283249$51,5|0,0|TOTAL PAGADO|VENT30$VENT30|PROD03|6|6,50|39,00$VENT30|PROD09|2|1,50|3,00';
	VENTASPLSQL.REGISTRAR_VENTA(V_PRUEBA,V_COD_RPTA,V_MENSAJE);
	DBMS_OUTPUT.PUT_LINE('COD: '||V_COD_RPTA);
	DBMS_OUTPUT.PUT_LINE('MENSAJE: '||V_MENSAJE);
END;

/*
FORMATO:
---------
CLIENTE: 'S|68597849|PEREZ AGUILAR|DIEGO|AV LUCCINI 546 SAN ISIDRO|diegoperez@gmail.com|487-4723$
VENTA: 		VENT20|51.5|FACT001|68597849$
PAGO:			51.5|0.0|TOTAL PAGADO|VENT20$
DETALLE: 	VENT20|PROD01|6|6.50|39.00$
DETALLE: 	VENT20|PROD06|2|1.50|3.00'
*/