
CREATE OR REPLACE TRIGGER SCOTT.TR_DENY_DROP
BEFORE CREATE OR DROP ON SCHEMA 
BEGIN
  RAISE_APPLICATION_ERROR( -20000, 'NO ES POSIBLE BORRAR OBJETOS.'); 
END TR_DENY_DROP;


CREATE TABLE scott.algo( a VARCHAR2(50) );

DROP TABLE SCOTT.SALGRADE;

DROP USER SCOTT CASCADE;


