
CREATE TABLESPACE TBS_YUCRA DATAFILE 'E:\Users\Oracle\Documents\ExFinal\Scripts\YUCRA.DBF' SIZE 100M;
CREATE USER USUARIOYUCRA IDENTIFIED BY 1234 DEFAULT TABLESPACE TBS_YUCRA;

GRANT CONNECT,RESOURCE TO USUARIOYUCRA;
GRANT CREATE TABLE TO USUARIOYUCRA;
GRANT CREATE VIEW TO USUARIOYUCRA;

ALTER USER USUARIOYUCRA QUOTA UNLIMITED ON TBS_YUCRA;