
CREATE OR REPLACE PACKAGE USUARIOYUCRA.PKG_UTIL AS
	TYPE T_ARRAY_STRING IS TABLE OF VARCHAR2(1000) 
	INDEX BY BINARY_INTEGER;

	FUNCTION SPLIT(P_DATA VARCHAR2, P_DELIMITADOR VARCHAR2 ) 
	RETURN T_ARRAY_STRING;

END PKG_UTIL;

CREATE OR REPLACE PACKAGE BODY USUARIOYUCRA.PKG_UTIL AS
	FUNCTION SPLIT(P_DATA VARCHAR2, P_DELIMITADOR VARCHAR2 ) 
	RETURN T_ARRAY_STRING
	IS
	    I        NUMBER   := 0;
	    POS      NUMBER   := 0;
	    V_DATA   CLOB     := P_DATA;
	    STRINGS  T_ARRAY_STRING;
	BEGIN
	  V_DATA := TRIM( V_DATA );
	  POS := INSTR( V_DATA, P_DELIMITADOR, 1, 1 );
	  WHILE ( POS != 0) LOOP
	      I := I + 1;
	      STRINGS(i) := SUBSTR( V_DATA, 1, POS - 1 );
	      V_DATA :=  SUBSTR( V_DATA, POS + 1, LENGTH(V_DATA) );
	      pos := instr(V_DATA, P_DELIMITADOR, 1, 1);
	      IF POS = 0 THEN
	          STRINGS( I + 1 ) := V_DATA;
	      END IF;    
	  END LOOP;
	  IF I = 0 AND LENGTH( V_DATA ) > 0 THEN
	    STRINGS( I + 1 ) := V_DATA;
	  END IF;
	  RETURN strings;
	END SPLIT;
	
END PKG_UTIL;

CREATE OR REPLACE PROCEDURE PR_INSERTA_PRODUCTO
( P_DATOS IN VARCHAR2 )
AS
  V_FILAS    PKG_UTIL.T_ARRAY_STRING;
  V_CAMPOS   PKG_UTIL.T_ARRAY_STRING;
  
BEGIN
  V_FILAS := PKG_UTIL.SPLIT(P_DATOS,'¬');
  FOR I in 1 .. V_FILAS.COUNT LOOP 
    
    V_CAMPOS := PKG_UTIL.SPLIT(V_FILAS(I),'|');
    
    INSERT INTO PRODUCTO(CODIGO_PRODUCTO,NOMBRE_PRODUCTO,DESCRIPCION_PRODUCTO,PRECIO_PRODUCTO,STOCK_PRODUCTO)
    VALUES(V_CAMPOS(1), V_CAMPOS(2), V_CAMPOS(3), CAST(to_number(V_CAMPOS(4)) AS FLOAT), CAST(to_number(V_CAMPOS(5)) AS NUMBER(38)) );
  END LOOP;
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('PROCESO OK');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    ROLLBACK;
END;


DECLARE
  V_DATOS VARCHAR2(6000);
BEGIN
  V_DATOS := 'P0000012|crema dental|dento triple accion|10.5|60¬P0000013|bloqueador solar|spf neutrogena|54.00|153¬P0000014|jabon tripack|avena nivea|8.10|80';
  PR_INSERTA_PRODUCTO (V_DATOS);
END;
commit;











