
CREATE OR REPLACE FUNCTION scott.FN_SUMA_CUADRAD
(P_NUM IN NUMBER) RETURN NUMBER
IS
V_SUMA NUMBER:= 0;
V_NUM NUMBER := P_NUM;
BEGIN 

WHILE(V_NUM <> 0) LOOP
    V_SUMA := V_SUMA + V_NUM*V_NUM;
    V_NUM := V_NUM - 1;
END LOOP;

RETURN V_SUMA;

END;

SELECT FN_SUMA_CUADRAD(4) FROM DUAL