--TAREA 2

/* CREAR UNA FUNCION PARA ENCONTRAR LA SUMA DE 
LOS CUADRADOS DE LOS N 1ROS NUMEROS ENTEROS POSITIVOS*/
CREATE OR REPLACE FUNCTION SCOTT.FN_CUADRADOS   
(P_NUM NUMBER) RETURN NUMBER
IS
	v_suma NUMBER :=0;
	v_num NUMBER:= P_num;  
BEGIN

	WHILE(V_NUM>=0) LOOP
			V_SUMA := v_suma +	v_num *	v_num; 
			v_num:= v_num -1; 
	END LOOP;
	RETURN v_suma;
END;

---prueba
SELECT FN_CUADRADOS(5) FROM DUAL