CREATE OR REPLACE FUNCTION SCOTT.FN_SUMA_CUADRADOS_POSITIVOS(P_NUM NUMBER) RETURN NUMBER
IS
	V_SUMA NUMBER:=0;
	V_NUM NUMBER := P_NUM;
BEGIN
	IF(V_NUM<0)THEN 
	  V_NUM:=V_NUM * -1; 
	END IF;
	
	LOOP
		V_SUMA := V_SUMA + V_NUM * V_NUM;
		V_NUM := V_NUM -1;
		EXIT WHEN (V_NUM=0);
	
	END LOOP;
	RETURN V_SUMA;
END;
/

SELECT SCOTT.FN_SUMA_CUADRADOS_POSITIVOS(-3) FROM DUAL;

