CREATE OR REPLACE PROCEDURE RECURSOS.PR_UPD_SUELDO
(	P_IDEMP IN EMPLEADO.IDEMPLEADO%TYPE,
	P_INCR IN NUMBER)
IS
	V_SUELD_MAX CARGO.SUELDO_MAX%TYPE := 0;
	V_SUELDO EMPLEADO.SUELDO%TYPE := 0;
	V_SUELDO_NUEVO CARGO.SUELDO_MAX%TYPE := 0;
BEGIN
	
	SELECT C.SUELDO_MAX, E.SUELDO 
	INTO V_SUELD_MAX, V_SUELDO
	FROM CARGO C 
	INNER JOIN EMPLEADO E ON E.IDCARGO = C.IDCARGO
	WHERE E.IDEMPLEADO = P_IDEMP;
	
	V_SUELDO_NUEVO := V_SUELDO + P_INCR;
	IF (V_SUELDO_NUEVO > V_SUELD_MAX) THEN
		RAISE_APPLICATION_ERROR(-20001, 'Sueldo supera el máximo del cargo');
	END IF;
	
	UPDATE EMPLEADO
		SET SUELDO = V_SUELDO_NUEVO
		WHERE IDEMPLEADO = P_IDEMP;
	COMMIT;
	DBMS_OUTPUT.PUT_LINE('Proceso OK');
EXCEPTION
	WHEN OTHERS THEN
	  ROLLBACK;
		DBMS_OUTPUT.PUT_LINE('CODIGO: ' || TO_CHAR(SQLCODE));
		DBMS_OUTPUT.PUT_LINE('MENSAJE: ' || SQLERRM);
END;

BEGIN
	RECURSOS.PR_UPD_SUELDO('E0001',50000);
END;
