
CREATE OR REPLACE FUNCTION SCOTT.FN106(V_EMPNO EMP.EMPNO%TYPE) 
RETURN VARCHAR2 
IS
V_MSG VARCHAR2(40);
V_SAL EMP.SAL%TYPE;
BEGIN
SELECT SAL INTO V_SAL FROM EMP WHERE EMPNO=V_EMPNO;
CASE 
  WHEN (V_SAL > 0 AND V_SAL <= 2500) THEN
    V_MSG :=  'SALARIO BAJO';
   WHEN (V_SAL > 2500 AND V_SAL <= 4000) THEN
    V_MSG :=  'SALARIO BUENO';
   ELSE
    V_MSG:= 'CASO DESCONOCIDO';
   END CASE;
   V_MSG := TO_CHAR(V_SAL) || '-' || V_MSG;
   RETURN V_MSG;
END;


------------ PRUEBA ------------
SELECT FN106(7369) FROM DUAL;