
CREATE OR REPLACE FUNCTION SCOTT.FN_MCD
( P_NUM1 NUMBER, P_NUM2 NUMBER)
	RETURN NUMBER
IS
	V_NUM1 NUMBER := P_NUM1;
	V_NUM2 NUMBER := P_NUM2;
	V_REF NUMBER;
	V_MCD NUMBER;
BEGIN
	V_REF := V_NUM1;
	IF (V_NUM1 < V_NUM2) THEN 
		V_REF := P_NUM2;
	END IF;
	FOR N IN 1..V_REF LOOP
		IF (MOD(V_NUM1,N)=0 AND MOD(V_NUM2,N)=0) THEN
			V_MCD := N;
		END IF;		
	END LOOP;
	RETURN V_MCD;
END;

SELECT FN_MCD(20, 15) FROM DUAL;