/*
Tarea 

Desarrollar un procedimiento almacenado que
permita cagar empleados en la tabla
RECURSOS.EMPLEADO, el salario debe ser el
promedio entre el maximo y minimo segun su cargo.
*/

GRANT EXECUTE ON SCOTT.PKG_UTIL TO RECURSOS;


CREATE OR REPLACE PROCEDURE RECURSOS.SP_INSERTA_EMP2
( P_DATOS IN VARCHAR2 )
AS
  V_FILAS    SCOTT.PKG_UTIL.T_ARRAY_STRING;
  V_CAMPOS   SCOTT.PKG_UTIL.T_ARRAY_STRING;
  V_SAL_PROM NUMBER(7,2);
BEGIN
  V_FILAS := SCOTT.PKG_UTIL.SPLIT(P_DATOS,'¬');
  FOR I in 1 .. V_FILAS.COUNT LOOP 
    
    V_CAMPOS := SCOTT.PKG_UTIL.SPLIT(V_FILAS(I),'|');
    
    SELECT ((SUELDO_MIN+SUELDO_MAX)/2) INTO V_SAL_PROM
    FROM CARGO 
    WHERE IDCARGO = V_CAMPOS(4);
    
    INSERT INTO RECURSOS.EMPLEADO(IDEMPLEADO, APELLIDO, NOMBRE, FECINGRESO, IDCARGO, IDDEPARTAMENTO, SUELDO)
    VALUES(V_CAMPOS(1), V_CAMPOS(2), V_CAMPOS(3), SYSDATE,V_CAMPOS(4), V_CAMPOS(5), V_SAL_PROM );
    
  END LOOP;
  
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('PROCESO OK');
  
EXCEPTION

  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    ROLLBACK;

END;

SELECT * FROM RECURSOS.EMPLEADO;
SELECT * FROM RECURSOS.CARGO;

DECLARE
  V_DATOS VARCHAR2(6000);
BEGIN
  V_DATOS := 'E0095|CASTRO|PABLO|C01|103¬E0096|ACUNA|SULMA|C08|105¬E0097|SANCHEZ|SONIA|C03|101';
  RECURSOS.SP_INSERTA_EMP2(V_DATOS);
END;