
DECLARE

	TYPE REC_EMP IS RECORD (
		NAME VARCHAR2(100),
		SALARY NUMBER(10,2)
	);
	
	TYPE TBL_EMP IS TABLE OF REC_EMP 
		INDEX BY BINARY_INTEGER;
		
	V_EMPS TBL_EMP;
	V_CONT NUMBER := 0;
BEGIN
	-- LLENAR TABLA
	FOR R IN (SELECT * FROM RECURSOS.EMPLEADO) LOOP
		V_CONT := V_CONT + 1;
		V_EMPS(V_CONT).NAME := R.NOMBRE;
		V_EMPS(V_CONT).SALARY := R.SUELDO;
	END LOOP;

	-- MOSTRAR TABLA
	FOR I IN 1..V_EMPS.COUNT LOOP
		DBMS_OUTPUT.PUT_LINE(V_EMPS(I).NAME || ' - ' || V_EMPS(I).SALARY);
	END LOOP;

END;


SELECT * FROM HR.EMPLOYEES;
